export const START_SESSION_REQUEST = 'START_SESSION_REQUEST';
export const START_SESSION_SUCCESS = 'START_SESSION_SUCCESS';
export const START_SESSION_ERROR = 'START_SESSION_ERROR';
export const CLOSE_SESSION = 'CLOSE_SESSION';

export const MAKE_SEARCH_REQUEST = 'MAKE_A_SEARCH_REQUEST';
export const MAKE_SEARCH_SUCCESS = 'MAKE_A_SEARCH_SUCCESS';
export const MAKE_SEARCH_ERROR = 'MAKE_A_SEARCH_ERROR';

export const FETCH_ALBUM_REQUEST = 'FETCH_ALBUM_REQUEST';
export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS';
export const FETCH_ALBUM_ERROR = 'FETCH_ALBUM_ERROR';

export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST';
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS';
export const FETCH_ARTIST_ERROR = 'FETCH_ARTIST_ERROR';

export const FETCH_ARTIST_TOP_TRACKS_REQUEST = 'FETCH_ARTIST_TOP_TRACKS_REQUEST';
export const FETCH_ARTIST_TOP_TRACKS_SUCCESS = 'FETCH_ARTIST_TOP_TRACKS_SUCCESS';
export const FETCH_ARTIST_TOP_TRACKS_ERROR = 'FETCH_ARTIST_TOP_TRACKS_ERROR';

export const FETCH_ARTIST_RELATED_ARTISTS_REQUEST = 'FETCH_ARTIST_RELATED_ARTISTS_REQUEST';
export const FETCH_ARTIST_RELATED_ARTISTS_SUCCESS = 'FETCH_ARTIST_RELATED_ARTISTS_SUCCESS';
export const FETCH_ARTIST_RELATED_ARTISTS_ERROR = 'FETCH_ARTIST_RELATED_ARTISTS_ERROR';